spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #数据库索引
    database: 0
    host: 192.168.247.100
    port: 6379
    password: 123456

server:
  port: 80
